### ISSUE TITLE
Compatibility for TYPO3 version 12

### ISSUE THREAD

**Issue by kevin-appelt** [IchHabRecht/content_defender#110]
* Adjustment of dependency restrictions to TYPO3
* Adjustment of travis CI
* If necessary code adjustments

**Comment by h3nn3s** [comment]
Hi.
I did some tests on v12 dev-main. Everything works fine. I did not discover any problems so far.

Is there a chance to get support for v12.2 at least or even dev-main?

**Comment by h3nn3s** [comment]
Hi @IchHabRecht 
we are currently using TYPO3 v12 in dev-main branch - I think v12.2 will be released tomorrow

**Comment by h3nn3s** [comment]
Nice one.
Did not know this feature - thanks for pointing this out.
