### ISSUE TITLE
TYPO3 12 compatibility: Undefined array key error in TcaColPosItems.php on line 62

### ISSUE THREAD

**Issue by juergen-venne** [IchHabRecht/content_defender#140]
Edit a tt_content record in Backend results in error
`PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key 1 in /var/www/html/vendor/ichhabrecht/content-defender/Classes/Form/FormDataProvider/TcaColPosItems.php line 62`

The functionality is still given for colPos 0, since $x = []; echo (int)$x[1];' evaluates to 0.

Reason:
$item[1] on line 62 is not set because of the introduced array keys in:
https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Select/Properties/Items.html

This can be fixed by changing the line from
`$colPos = (int)$item[1];`
to 
`$colPos = (int)($item[1] ?? $item['value']);`

This change is considered to be fully compatible with TYPO3 10 and 11.

Of course, I can provide a pull request if you like :-)

**Comment by IchHabRecht** [comment]
Hi @juergen-venne 

If I understand your problem correctly, your problem should already be solved with https://github.com/IchHabRecht/content_defender/commit/a6a9a08606b8fcfc3c111d8a8e1f4d3b9695b19f
