### ISSUE TITLE
Versions/tags 3.4.4/3.4.5 confusion

### ISSUE THREAD

**Issue by mbrodala** [IchHabRecht/content_defender#154]
The [tags 3.4.4 and 3.4.5](https://github.com/IchHabRecht/content_defender/tags) seem to have been deleted on GH but are still [present on Packagist](https://packagist.org/packages/ichhabrecht/content-defender):

![image](https://github.com/IchHabRecht/content_defender/assets/5037116/c4c6d7e1-58b3-4f5a-bda9-f06baf843e17)

This should be fixed to be consistent again.

IMO tags should not be deleted again, even if they point to meaningless or broken releases. Various workflows and tools could get confused or create undefined results otherwise.

**Comment by IchHabRecht** [comment]
Hi @mbrodala 

Thanks for the hint. I deleted the nonexistent superfluous tags on Packagist
