### ISSUE TITLE
The sorting of content is not working

### ISSUE THREAD

**Issue by rrohaczek** [IchHabRecht/content_defender#22]
As soon as i activate content_defender the rearranging/sorting of content elements/plugins with drag and drop isn't getting saved at all.

Experienced this behavior with content_defender 2.2.3 on TYPO3 7.6.21 and TYPO3 8.7.4

**Comment by IchHabRecht** [comment]
Hi Rudolf,

Thank you for your report. Would you mind to test and verify the patch in branch https://github.com/IchHabRecht/content_defender/tree/correct-datamap-handling

**Comment by rrohaczek** [comment]
Hi Nicole,

works like a charm now (in 7.6.21 and 8.7.4)! Thank you very much!

**Comment by IchHabRecht** [comment]
Thank you for that fast feedback!

**Comment by mbrodala** [comment]
I can also confirm that the mentioned change fixes the issue.
