### ISSUE TITLE
Show error message earlier, if maximum element number is reached in one column

### ISSUE THREAD

**Issue by twllndr** [IchHabRecht/content_defender#28]
I limit the number of content elements in one column, which technically works fine. Process is as follows:

- Column is restricted to one element
- One element already created
- Editor clicks on "new content"
- Editor selects new element type
- Error message is shown, that maximum element number is reached.

Couldn't the error message be shown directly when the editor clicks on "new content"? In a flash message in the upper right corner for example? This would save a few extra clicks. Or maybe the "new content" button could be hidden directly or some kind of "deactivated" in that case?

(Tested it with TYPO3 8.7.6 and content_defender 2.2.3).

**Comment by IchHabRecht** [comment]
Hi Tobias,

Unfortunately the Core doesn't give any possibility to handle the restrictions in a better (earlier) place. Unfortunately it isn't also possible to simply don't show the "new content" button.
