### ISSUE TITLE
Don't show dropzones that aren't allowed for the content element you want to move (with drag and drop)

### ISSUE THREAD

**Issue by twllndr** [IchHabRecht/content_defender#3]
If I move a content element to a backend column, where it isn't allowed, I can drag it there and get an error message in the backend, that the content element couldn't be saved in this column. But after this move, the content element is shown in this not allowed column until you reload this page.

I think it would be better if you can't move it there in the first place. So the dropzones shouldn't be shown in that case.

**Comment by IchHabRecht** [comment]
Hi Tobias,

Your request is solved in TYPO3 8.7 already. IMHO it is a core bug that a JavaScript error doesn't reset the content element. As this is something related to the core's JavaScript, I decided it will not be part of this extension.
