### ISSUE TITLE
Content Defender breaks for specific beLayout configuration

### ISSUE THREAD

**Issue by josefglatz** [IchHabRecht/content_defender#37]
**TYPO3 Version**: 8.7 latest stable
**EXT Version**: 3.0.2
---
# Steps to reproduce it

## The following beLayout configuration makes EXT:content_defender working only partially

    mod {
    	web_layout {
    		BackendLayouts {
    			Default {
    				title = LLL:EXT:theme/Resources/Private/Language/locallang_backendlayouts.xlf:default.title
    				config {
    					backend_layout {
    						colCount = 12
    						rowCount = 2
    						rows {
    							1 {
    								columns {
    									1 {
    										name = LLL:EXT:theme/Resources/Private/Language/locallang_backendlayouts.xlf:col.sidebarDisabled
    										colPos =
    										colspan = 1
    									}
    									2 {
    										name = LLL:EXT:theme/Resources/Private/Language/locallang_backendlayouts.xlf:col.mainBesideSidebar
    										colPos = 5
    										colspan = 11
    										disallowed {
    											CType = list, miniFactbox, miniYoutube, miniImage, themeproject_sidebarEvents, themeproject_whats_happening, fullwidthImage
    										}
    									}
    
    								}
    							}
    							2 {
    								columns {
    									1 {
    										name = LLL:EXT:theme/Resources/Private/Language/locallang_backendlayouts.xlf:col.main
    										colPos = 0
    										colspan = 12
    										disallowed {
    											CType = list, miniFactbox, miniYoutube, miniImage, themeproject_sidebarEvents, themeproject_whats_happening
    										}
    									}
    								}
    							}
    						}
    					}
    				}
    				icon = theme-belayout-sidebar-content
    			}
    		}
    	}
    }

### Row 2 → Column 1 (only one) → colPos 0

... has no limitation.

**Comment by IchHabRecht** [comment]
Hi @josefglatz,

I think you are using colPos twice as row 1 -> column 1 doesn't have any colPos set which is turned to 0 by default.

**Comment by josefglatz** [comment]
Thanks for your answer Nicola :)

That's intentional. It is the way to only show placeholder areas in the page module.

content defender doesn't work with Row 2, Column 1. ..which is colPos = 0

**Comment by IchHabRecht** [comment]
Indeed I wasn't aware this is an intended way of configuration in backend layouts

**Comment by IchHabRecht** [comment]
@josefglatz Would you mind to test the associated branch/patch?

**Comment by josefglatz** [comment]
Of course!

Von meinem iPhone gesendet
