### ISSUE TITLE
Possibility to select allowed content elements in the backend layout wizard

### ISSUE THREAD

**Issue by twllndr** [IchHabRecht/content_defender#4]
For an integrator, who creates backend layouts in the TYPO3 backend, it would be very useful, to have a multi-select-box available, where the allowed elements could be selected directly.

![backend-layout-wizard](https://cloud.githubusercontent.com/assets/63435/25821529/bfb4717c-3435-11e7-89bc-659bfb1425c2.png)

**Comment by IchHabRecht** [comment]
Unfortunately this isn't possible with a whole PHP and JavaScript hack of the core files. I decided this will not be the scope of this extension. I think you should store your backend layouts within your versioning system and do not use/need the wizard at all.
