### ISSUE TITLE
Maxitems and Translations

### ISSUE THREAD

**Issue by Skinwalker** [IchHabRecht/content_defender#42]
**Testcase:**
Set column maxitems = 1
Add 1 content element to default language -> works
Translate the content element into another language -> works not
_Error: Maximum number of allowed content elements (1) reached_

I think the problem is that translations are related to the default ce and therefore the item count increases with every translation.

**Versions:**
TYPO3 - 8.7.10
Content_Defender - 3.0.3

**Comment by IchHabRecht** [comment]
Hi @Skinwalker,

Thanks for your report. Your issue should be solved with the new changes in #41.

Would you mind to test branch https://github.com/IchHabRecht/content_defender/tree/fix-maxitems-handling and see if everything works out for you and your configuration.

Thanks in advance!
