### ISSUE TITLE
Add restriction for single list types

### ISSUE THREAD

**Issue by twllndr** [IchHabRecht/content_defender#5]
Currently you can just allow/disallow the "list" ctype as a whole. But if you want single plugins to be allowed, while the rest should be disallowed, this isn't possible right now.

This feature is currently missing from EXT:gridelements too. Here is a ticket about a possible integration with a colon syntax or something like "allowedListTypes".
https://forge.typo3.org/issues/77549

EXT:gridelements itself has a plugin from type "gridelements_pi1" with certain grid types (can be created and named individually). They can be restricted individually with "allowedGridTypes". Don't know how to deal with such cases, but it would be nice, to have some generic(?) way to handle those custom type restrictions.

**Comment by fgerards** [comment]
+1 for that.
In TemplaVoila you had the extension "fcecolumns", which allows you to select FCE/CE types for each column of a container FCE/content column. This functionality is a must-have for large enterprise sites with 100s of editors and a set of 100+ FCE/CE-types.

I enhanced fcecolumns to work recursively in nested FCEs back in 2011, but this code is ofc not adaptable to the core/backnd layout concept of handling constraints for columns.

Is there a plan to go into the details of ContentElement/DCE/FCE-types ?
I would surely help implementing it.

**Comment by IchHabRecht** [comment]
Hi fgerards,

In my opionen custom content elements should be added as an own CType. So this extension already handles them. I don't want to support any third party elements type. The restriction handling should be implemented in those extensions on their own.

**Comment by IchHabRecht** [comment]
Hi,

I added a way how items can be restricted. Would you mind to test the new backend_layout configuration and give me some feedback if this works for you? Thank you in advanced.

**Comment by twllndr** [comment]
Hi Nicole,

I tested it with 7.6.18 and CType/list_type restrictions and it worked in every case. Well done!

Thx
Tobi
