### ISSUE TITLE
Compatible with TYPO3 9.3?

### ISSUE THREAD

**Issue by mbrodala** [IchHabRecht/content_defender#50]
Currently this package cannot be installed with TYPO3 9.3. Does it need further tests or can the dependencies simply be updated?

**Comment by IchHabRecht** [comment]
Hi @mbrodala,

There is a pull request already but I'd like to test it manually before merging and releasing a new version. Try to work on it this week.

**Comment by mbrodala** [comment]
Indeed, didn't see that one. I'll also try to test ASAP.

**Comment by cheindl** [comment]
Any test results yet?

**Comment by ervaude** [comment]
Works with 9.3 and 9.4 ;)

**Comment by IchHabRecht** [comment]
Content defender 3.0.7 is already released and available for composer installations. Due to some composer problems the TER upload failed and I didn't have any time to debug it currently.

**Comment by ervaude** [comment]
I saw that - but 3.0.7 is not compatible with TYPO3 9.4, right?

(I know this issue is about 9.3 but time moves on so quickly and also I figured you dont need an Issue for every TYPO3 release. I just tested in 9.4 and everything looks fine 👍 )

**Comment by IchHabRecht** [comment]
I still need an updated testing-framework to raise compatibility. Please wait until released ;-)

**Comment by IchHabRecht** [comment]
Content defender 3.0.8 was released now and adds compatiblity to TYPO3 9.4.

**Comment by mbrodala** [comment]
Thanks for the update!

**Comment by twllndr** [comment]
When doing a `composer require ichhabrecht/content-defender` I get version 4.1.0 now. Don't know if this is intended. I'm just curious, as you wrote you released 3.0.8.

**Comment by mbrodala** [comment]
@twllndr I assume this was a confusion with `nimut/testing-framework` 4.1.0. ;-)
