### ISSUE TITLE
Space after coma in allowed CTypes

### ISSUE THREAD

**Issue by stat1x** [IchHabRecht/content_defender#51]
Are you sure it works when you put a space after the coma in allowed CTypes as mentioned in the documentation like this : 

```
columns {
    1 {
        name = Column with header and textmedia elements
        colPos = 3
        colspan = 6
        allowed {
            CType = header, textmedia, div
        }
    }
}
```

By my side I am unable to drag and drop element in backend if I do so (it works only for the first element).

I had to write it like this : 
```
columns {
    1 {
        name = Column with header and textmedia elements
        colPos = 3
        colspan = 6
        allowed {
            CType = header,textmedia,div
        }
    }
}
```

**Comment by IchHabRecht** [comment]
Hi @stat1x,

Thank you for your request. For all explodes GeneralUtility::trimExplode is used. So all values are exploded by "," and get trimmed afterwards. So yes, I'm sure it works like mentioned in the documentation.

**Comment by stat1x** [comment]
Mmmh ok... So where can the problem come from? I have gridelements installed maybe?

**Comment by stat1x** [comment]
I tried to uninstall gridelements and I was able to drag and drop stuff again (even with space in CType list). So the issue is related to gridelements. I will report it now and close this one.
