### ISSUE TITLE
Content element is saved in wrong colPos

### ISSUE THREAD

**Issue by marvinhuebner** [IchHabRecht/content_defender#56]
After i add a new content element and save the content element, it gets saved into the wrong colPos.

![kapture 2018-10-29 at 16 42 08](https://user-images.githubusercontent.com/13386633/47661598-a3d62600-db99-11e8-8719-ae4cf34ae3fd.gif)

Our backend layout config looks like this: 

```
mod {
  web_layout {
    BackendLayouts {
      industry_standards_search {
        title = Industry Standards Search
        config {
          backend_layout {
            colCount = 1
            rowCount = 5
            rows {
              1 {
                columns {
                  1 {
                    name = Header
                    colPos = 1
                    allowed {
                      CType = mask_simple_header
                      list_type = industrystandards_header
                    }
                  }
                }
              }
              2 {
                columns {
                  1 {
                    name = Inhalt
                    rowspan = 3
                    colPos = 0
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

TYPO3 9.5.0
Content Defender 3.0.9

**Comment by IchHabRecht** [comment]
Hi @marvinhuebner,

The column that chosen before saving your content element is already "Inhalt". So the column "Header" is removed. Please check your configuration. Your require list_type to be set to industrystandards_header but I guess it is empty for an element of type mask_simple_header.

You can either change your configuration to list_type = ,mask_simple_header or use/test the branch https://github.com/IchHabRecht/content_defender/tree/process-showitems-only.

BTW: dealing with list type is explained in the README.md ;-)

**Comment by marvinhuebner** [comment]
Hi @IchHabRecht,

i haven't seen that my content element is already in "Inhalt". Now I've changed my config to the following:

```
allowed {
    CType = mask_simple_header, list
    list_type = industrystandards_header, mask_simple_header
}
```

This does not work with v3.0.9, but i've already tested it with [process-showitems-only](https://github.com/IchHabRecht/content_defender/tree/process-showitems-only) and then it works with the config above.

**Comment by IchHabRecht** [comment]
Hi @marvinhuebner,

I'm not sure if you save the leading colon in by configuration proposal. You need to explicitly allow an empty value for CTypes other than list.

**Comment by marvinhuebner** [comment]
Ah yes, i've overseen the leading comma in your configuration proposal. Will test it end of the week again.

**Comment by marvinhuebner** [comment]
I've tested it again with the leading comma, this does work for the list type `industrystandards_header` but `mask_simple_header` gets automatically moved to the column "Inhalt [0]" instead of "Header [1]".

```
allowed {
    CType =  ,mask_simple_header, list
    list_type = industrystandards_header
}
```

But it works with the #55, so i will close the issue now. Thanks for your great work!
