### ISSUE TITLE
The record "%s" couldn\'t be saved due to disallowed value(s).

### ISSUE THREAD

**Issue by gerchomat** [IchHabRecht/content_defender#57]
The combination of restricted list_type and "normal" CType does not work as expected.

Allowed-Configuration
`CType = div,list`
`list_type = news_pi1`

At first time the normal-CE (div) is being created, the error does not show.
Since the second save the error appears. 

TYPO3: 9.5.4
Content Defender: 3.0.9

**Comment by gerchomat** [comment]
I did a lookup in the code and found out the error comes from

https://github.com/IchHabRecht/content_defender/blob/79ef843b2f2a8c07e7122fb1ca90b0d744cdda0f/Classes/Hooks/AbstractDataHandlerHook.php#L104-L109

The Problem is that if you have `CType` and `list_type` and save a normal-CE it has an empty `list_type` and the conditions will fail.

**Comment by gerchomat** [comment]
A short (but not very nice) fix is if i wrote `list_type = news_pi1,` with an extra comma at the end, so the condition is true for every normal-CE without a list_type

**Comment by IchHabRecht** [comment]
Hi @gerchomat,

Thank you for your report. The issue you describe should be fixed with the commit https://github.com/IchHabRecht/content_defender/commit/45fec68ae14963a4343c5c57cd80fb6576c93495 that only processes shown field. Is the list_type field shown if a div element is selected?

**Comment by IchHabRecht** [comment]
I just saw that this commit isn't released yet. Would you mind to test it? ^^

**Comment by gerchomat** [comment]
> I just saw that this commit isn't released yet. Would you mind to test it? ^^
Yes, the commit https://github.com/IchHabRecht/content_defender/commit/45fec68ae14963a4343c5c57cd80fb6576c93495 works

**Comment by IchHabRecht** [comment]
I finally managed to release a new version. Closing this ticket as resolved.
