### ISSUE TITLE
Limiting to single gridelement layout causes error

### ISSUE THREAD

**Issue by philippwise** [IchHabRecht/content_defender#58]
Hi

I found a bug using PHP 7.2, TYPO3 9.5.5, content_defender 3.0.10 and gridelements 9.1.1

When limiting a backend layout column to a single gridelement layout with 
```
allowed {
  CType = gridelements_pi1
  tx_gridelements_backend_layout = IDENTIFIER
}
```
adding the gridelement causes an error.

```
TypeError
array_filter() expects parameter 1 to be array, null given

in PATH/typo3conf/ext/content_defender/Classes/Form/FormDataProvider/TcaCTypeItems.php line 50
```
Only the right gridelement layout is selctable, but when selecting it the Error ist thrown.

Without contentdefender this configuration works.

Thank you very much in advance.

Greetings Philipp

**Comment by kassor** [comment]
Same problem here

**Comment by IchHabRecht** [comment]
Hi @philippwise, @kassor,

I do not use gridelements, but doesn't it provide its own way of allowing and denying content elements? What is the purpose of using content_defender together with gridelements? Thanks for your help.

**Comment by obi12341** [comment]
same problem here. we had to revert the release

**Comment by IchHabRecht** [comment]
Maybe you saw th open pull request already? Would be really cool if somebody of you could test this pull request (branch https://github.com/IchHabRecht/content_defender/tree/process-itemsProcFunc-items) and tell me if it solves the problems. Thank you very much in advanced.
