### ISSUE TITLE
Hook for add additional logic from other extensions

### ISSUE THREAD

**Issue by jmverges** [IchHabRecht/content_defender#65]
Hi,

I would like to suggest some hook between:

~~https://github.com/IchHabRecht/content_defender/blob/master/Classes/Form/FormDataProvider/TcaCTypeItems.php#L38
https://github.com/IchHabRecht/content_defender/blob/master/Classes/Form/FormDataProvider/TcaCTypeItems.php#L39~~ 
 
https://github.com/IchHabRecht/content_defender/blob/master/Classes/BackendLayout/BackendLayoutConfiguration.php#L70

In that way, other extensions could make additional logic in there.

Thanks,

**Comment by IchHabRecht** [comment]
Hi @jmverges,

Would you mind to describe for what reason you would need any hook? IHMO the logic is solid and connected to existing core configuration.

**Comment by jmverges** [comment]
Hi @IchHabRecht,

I agree about the logic is solid for the core. However there are scenarios where other extensions are in place. To be able to hook data from other extensions would be the best case.

My current options are:
1) Fork this extension
2) Remove this extension
3) Leave it as I have it now, where the extension is consistent but I cannot make consistent nested data from other extension.

**Comment by froschdesign** [comment]
@jmverges 
Can you provide a concrete example / use case?

**Comment by IchHabRecht** [comment]
Hi @jmverges,

I really would like to help you, but without any real example/hook I'm not able to understand your problem. I guess there should be another way for your case to be resolved, without any need to change content_defender.

**Comment by jmverges** [comment]
Hi @IchHabRecht,

I'm working in a project that I didn't kickstart and it is working with Core Backend Layouts and Content Defender. 

Now I've been told to put Flux. I'm a Flux guy but I'm trying to respect the work done by other developer instead of rework it and leave Backend Layouts and Content Defender.

**It is the first time I see Content Defender, and I like it.**

Thats why I'm writing here and suggesting that, instead of making final the return resultant logic of elements to allow in CType select, wizard, copy paste, etc be able to hook in there any other extension to modify if needed that logic (which in most of the cases **or all core cases** is correct)

It's just a suggestion to better interconnectivity with other extensions and use cases.

**Comment by IchHabRecht** [comment]
Hi @jmverges,

Thank you very much for your fast reply. Still I don't get the problem. In backend layout configuration you can define certain allowed or disallowed values and/or maximum number of items. As far as I know flux allows you to define new content elements. If you need to allow/disallow those elements, you would need to change your backend layout configuration. I don't see any reason why you should bypass that configuration and allow other elements here. If you need to change the configuration "on the fly" I would suggest to use a hook within the backend layout concept and change the content_defender configuration as needed.

Hope this helps a bit to resolve your problem. If you don't mind I would be really interested in your concrete problem using Flux.

**Comment by jmverges** [comment]
Hi @IchHabRecht, 
is for nested contents. Flux is using calculated colPos for nested based on the UID of the parent element  (ie, a 3 columns with id 56738) + the colPos of the 2nd column. The nested content (ie, a Text CE) is having a colPos 5673802 (56738 from parent content, 02 for the second column in the 3 column element)

That column isn't find in the Backend Layout, so the logic is bypass and shows everything.

I was wondering that if not config was found in the Backend Layout then trigger something and put in there any logic another extension (like my very own site_template) could do for fitting both extensions together. Later I though that, instead of triggering when no config was found, trigger always.

**Comment by IchHabRecht** [comment]
Hi @jmverges,

Thank you very much for your clarification. Now I'm able to understand that it is about to extend the concept of content defender to other extensions that provide own column handling. I will think about a proper solution for me and come back to you.

**Comment by jmverges** [comment]
Hi @IchHabRecht,

Thank you, appreciate it.

**Comment by jmverges** [comment]
@IchHabRecht thank you!
