### ISSUE TITLE
Not compatible with ext:workspaces

### ISSUE THREAD

**Issue by infabo** [IchHabRecht/content_defender#67]
Given you have restricted a backend layout column to `maxitems = 1`, you won't be able to edit the containing CE record in a workspace.

It quits with:
![image](https://user-images.githubusercontent.com/3999104/85296473-be14f400-b4a1-11ea-84c5-29e05f4a9bb7.png)

**Comment by IchHabRecht** [comment]
Hi @infabo,

As I currently don't have any option to test workspace support, could you try the attached patch and if everything is working for you now. Thank you very much.

**Comment by infabo** [comment]
Hey @IchHabRecht, your PR solves my described problem. Now one is able to edit an existing CE.

However, I just discovered another case which leads to the same error-message as reported above, prerequisites are the same (one CE, maxitems=1):

* delete the one existing CE in the workspace environment
* and afterwards add/create a new CE

-> Maximum number of allowed content elements (1) reached. 1494605357

**Comment by infabo** [comment]
The max-indicator looks fine:

![image](https://user-images.githubusercontent.com/3999104/85666202-73bb8f00-b6bc-11ea-861c-b75ffeb17419.png)

The wizard shows a possible CE too:

![image](https://user-images.githubusercontent.com/3999104/85666265-8635c880-b6bc-11ea-9f61-2e396249594e.png)

But finally:

![image](https://user-images.githubusercontent.com/3999104/85666315-92218a80-b6bc-11ea-9d0f-6c45b368bdd6.png)

**Comment by IchHabRecht** [comment]
Hi @infabo,

With the updated pull request everything should be fine now. Would you mind to test again?

**Comment by infabo** [comment]
Okay, I will have a look ASAP
