### ISSUE TITLE
Cannot move records in "Languages" view with defLangBinding

### ISSUE THREAD

**Issue by mbrodala** [IchHabRecht/content_defender#73]
When using the "Languages" view of the Page module with `mod.web_layout.defLangBinding` enabled, reordering content elements via drag and drop fails:

```
1: The record "<content title>" couldn't be saved due to disallowed value(s).
```

(Appears twice)

Evidently the following data is built in [`DragDrop.onDrop`](https://github.com/TYPO3/TYPO3.CMS/blob/v9.5.22/typo3/sysext/backend/Resources/Private/TypeScript/LayoutModule/DragDrop.ts#L169):

```
cmd[tt_content][254][move]: -10
data[tt_content][254][colPos]: false
data[tt_content][254][sys_language_uid]: NaN
```

(Here `10` is the UID of the content element after which the dragged element should be sorted)

It seems like these broken values are to be expected since they are the same on TYPO3v8 and on TYPO3v9. All `DataHandler` hooks will get a `colPos` of `"false"` (string) which makes all content elements invalid for any section, thus moving/reordering fails.

This works fine in the "Columns" view and with `defLangBinding` disabled however. In these cases the Page module has a quite different output which [includes the necessary `data-colpos` and `data-language-uid` attributes](https://github.com/TYPO3/TYPO3.CMS/blob/v9.5.22/typo3/sysext/backend/Classes/View/PageLayoutView.php#L937).

So it might be necessary to take these values into account in the `DataHandler` hooks and always load the actual values from the dragged record instead.

(I cannot test with TYPO3v10 ATM since `defLangBinding` enabled [makes all content elements disappear](https://forge.typo3.org/issues/90617).)

**Comment by mbrodala** [comment]
This issue has been fixed in TYPO3 itself now: https://review.typo3.org/c/Packages/TYPO3.CMS/+/66015

**Comment by IchHabRecht** [comment]
@mbrodala,

Thanks for taking care. I already saw there was a patch for defLangBinding merged.
