### ISSUE TITLE
TYPO3 v11 compatibility

### ISSUE THREAD

**Issue by kevin-appelt** [IchHabRecht/content_defender#79]
- An installation on TYPO3 v11.1 worked without problems.
- The extension scanner in the TYPO3 backend does not show any messages.
- The functionality is also given as far as I can tell - tested with b13/container and TYPO3 backend layouts

It would be wonderful if there was either a release or the dev-master (or something similar) was usable for now.

**Comment by IchHabRecht** [comment]
Hi @kevin-appelt,

Thank you for your issue. Please feel free to add a pull request with the mandatory adjustments like Composer and Travis CI changes. As Travis CI doesn't work currently, I can run tests locally to check if everything is running with a current TYPO3 11.1 release.
