### ISSUE TITLE
Adding allowed.CType breaks drag'n'drop in our backend (TYPO3 10.4.16)

### ISSUE THREAD

**Issue by Jashi** [IchHabRecht/content_defender#83]
We are working a lot with page types and backend layouts and allowing specific CTypes inside a backend layout area - basically what I assumed this extension could help us with.

Now adding a config like the one in the docs works and does not allow us to add other content elements. Unfortunately it also does not allow us to drag and drop content elements within that area anymore. I can still drag them to e.g. a gridelement which has no "allowed" config and back outside though. Otherwise the "orange/green" drag and drop area simply never appears.

I tried disallow instead and that actually works, so I do have a workaround - it's just not a pretty one as I have to list all content elements but the one allowed. Any idea what the problem could be?

**Comment by IchHabRecht** [comment]
Hi @Jashi,

Thank you for your issue. I have checked the current version of content_defender with TYPO3 10.4.17. As there isn't any code changed by content_defender I would image that there's maybe some interferences with gridelements. AFAIK gridelements uses its own configuration for content handling handling and both extensions might not be usable together.

**Comment by Jashi** [comment]
Thanks for the feedback. It was indeed a problem together with gridelements.
Loading gridelements before content_defender => broken drag and drop
Loading content_defender before gridelements => everything works
