### ISSUE TITLE
Add support for Typo3 11.5 LTS

### ISSUE THREAD

**Issue by kosimas** [IchHabRecht/content_defender#90]
Hey, support for the newest LTS Version would be awesome!
Related: #86

**Comment by hxkxn** [comment]
That would be really helpful, because I cannot update my CMS without it. Thanks a lot in advance.

**Comment by kosimas** [comment]
> That would be really helpful, because I cannot update my CMS without it. Thanks a lot in advance.
You can clone the repo and replace the following line inside the composer.json file
`"typo3/cms-backend": "^8.7 || ^9.5 || ^10.4 || ~11.1.0 || ~11.2.0"`
with
`"typo3/cms-backend": "^8.7 || ^9.5 || ^10.4 || ^11.5"`

For me everything works as as expected. No errors or problems so far.
