### ISSUE TITLE
Enable PHP 8.1 support for TYPO3 11.5 LTS

### ISSUE THREAD

**Issue by goldi42** [IchHabRecht/content_defender#94]
Enable PHP 8.1 support for TYPO3 11.5 LTS to support this service combination.

**Comment by brosua** [comment]
When will PHP 8.1 be supported? Is there anything I can do to help?

**Comment by ingeniumdesign** [comment]
yes, we need a PHP 8.1 support, Thanks

**Comment by IchHabRecht** [comment]
Hi @brosua and @ingeniumdesign 
It's always a pleasure to help out. Actual the current tests are failing with latest TYPO3 versions and I need to find out how to solve those problems. Thanks for your help anyway!

**Comment by IchHabRecht** [comment]
Feel free to update.
